name: erlang

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:

    runs-on: ubuntu-latest
    name: OTP ${{matrix.otp}}
    strategy:
      matrix:
         otp: ["22", "23", "24"]

    container:
      image: erlang:${{matrix.otp}}

    steps:
    - uses: actions/checkout@v2
    - name: Compile
      run: "rebar3 compile"
    - name: Find unused code
      run: "rebar3 hank"
    - name: XRef
      run: "rebar3 xref"
    - name: Dialyzer
      run: "rebar3 dialyzer"
    - name: Solve puzzles
      run: "rebar3 eunit"

    - name: "Publish Unit Test Results"
      uses: EnricoMi/publish-unit-test-result-action@v1.23
      if: always()
      with:
        files: TEST-*.xml
